import { expect, test } from '@playwright/test'

test('实例密码与查看账号流程不保存密码到浏览器', async ({page}, testInfo) => {
  await page.goto('/#/i/testpilot/task/Alas')
  const panel = page.getByTestId('account-panel')
  await expect(panel.getByRole('heading', {name: '账号管理', exact: true})).toBeVisible()
  await expect(panel.getByRole('button', {name: '设置实例密码', exact: true})).toBeDisabled()
  const password = 'Browser-Test-Passphrase-81!'
  await panel.locator('#account-password').fill(password)
  await panel.locator('#account-confirm').fill(password)
  await panel.getByRole('button', {name: '设置实例密码', exact: true}).click()
  await expect(panel.getByRole('switch')).toHaveAttribute('aria-checked', 'false')
  await expect(panel.locator('#account-password')).toHaveValue('')
  await expect(panel.getByRole('button', {name: '验证密码并查看账号', exact: true})).toBeDisabled()
  await panel.locator('#account-password').fill(password)
  await panel.getByRole('button', {name: '验证密码并查看账号', exact: true}).click()
  await expect(panel.getByText('尚无账号快照。请先在游戏中登录，再备份。', {exact: true})).toBeVisible()
  await expect(panel.locator('#account-password')).toHaveValue('')
  await panel.getByRole('button', {name: '隐藏账号信息', exact: true}).click()
  await expect(panel.getByText('尚无账号快照。请先在游戏中登录，再备份。', {exact: true})).toHaveCount(0)
  expect(await page.evaluate(() => JSON.stringify({local: {...localStorage}, session: {...sessionStorage}}))).not.toContain(password)
  await panel.getByRole('button', {name: '清除内存解锁', exact: true}).click()
  await expect(panel.getByText('内存未解锁 · 未绑定 TPM', {exact: true})).toBeVisible()
  await panel.locator('#account-password').fill(password)
  await panel.getByRole('button', {name: '绑定本机 TPM 自动解锁', exact: true}).click()
  await expect(panel.getByText('账号保险库的盐和数据库已销毁，启动已阻止。请重新设置实例密码并备份账号。', {exact: true})).toBeVisible()
  await expect(panel.getByRole('button', {name: '验证密码并查看账号', exact: true})).toHaveCount(0)
  await expect(panel.getByRole('button', {name: '设置实例密码', exact: true})).toBeVisible()
  await panel.screenshot({path: testInfo.outputPath('account-desktop.png'), animations: 'disabled'})
  await page.setViewportSize({width: 390, height: 844})
  await expect(panel).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await panel.screenshot({path: testInfo.outputPath('account-mobile.png'), animations: 'disabled'})
  const replacement = 'Replacement-Browser-Passphrase-93!'
  await panel.locator('#account-password').fill(replacement)
  await panel.locator('#account-confirm').fill(replacement)
  await panel.getByRole('button', {name: '设置实例密码', exact: true}).click()
  await expect(panel.getByRole('switch')).toHaveAttribute('aria-checked', 'false')
  await expect(panel.getByText('账号保险库的盐和数据库已销毁，启动已阻止。请重新设置实例密码并备份账号。', {exact: true})).toHaveCount(0)
  await panel.locator('#account-password').fill(replacement)
  await panel.getByRole('button', {name: '验证密码并查看账号', exact: true}).click()
  await expect(panel.getByText('尚无账号快照。请先在游戏中登录，再备份。', {exact: true})).toBeVisible()
})
