import { expect, test } from '@playwright/test'

test('总览三态、资源搭配记忆、日志与被动截图切换', async ({page}) => {
  const methods: string[] = []
  page.on('websocket', socket => socket.on('framesent', frame => { methods.push(JSON.parse(String(frame.payload)).method) }))
  await page.goto('/#/i/demo-main/overview')
  await expect(page.getByLabel('搜索日志')).toBeVisible()
  await expect(page.locator('.primary-nav').getByRole('link', {name: '运行日志'})).toHaveCount(0)
  await page.getByRole('button', {name: '配置资源', exact: true}).click()
  await page.getByRole('dialog').getByLabel('行动力', {exact: true}).check()
  await page.getByRole('button', {name: '完成', exact: true}).click()
  await expect(page.locator('.resource-card')).toHaveCount(5)
  await page.reload()
  await expect(page.locator('.resource-card')).toHaveCount(5)
  await page.getByRole('button', {name: '启动调度器', exact: true}).click()
  await expect(page.locator('.task-state.running')).toHaveCount(1)
  await expect(page.locator('.task-state.pending').first()).toBeVisible()
  await expect(page.locator('.task-state.waiting').first()).toBeVisible()
  await page.getByRole('tab', {name: '截图', exact: true}).click()
  await expect(page.getByAltText('任务最近一次截图')).toBeVisible({timeout: 10000})
  expect(methods).not.toContain('preview.capture')
  await page.screenshot({path: 'test-results/overview-preview-new.png', fullPage: true})
  await page.getByRole('tab', {name: '日志', exact: true}).click()
  await page.getByLabel('搜索日志').fill('模拟调度器已启动')
  await expect(page.locator('.log-line')).toHaveCount(1)
  await page.getByRole('button', {name: '停止运行', exact: true}).click()
  await page.getByLabel('搜索日志').fill('')
  await page.screenshot({path: 'test-results/overview-logs-new.png', fullPage: true})
  await page.goto('/#/i/demo-main/task/Main')
  await expect(page.locator('[id="Main.Emotion.Fleet1Record"]')).toHaveValue('2026-09-12 23:45:12.123456')
  await expect(page.locator('[id="Main.Emotion.Fleet1Record"]')).toHaveAttribute('readonly', '')
})

test('统计分类、K 线、时间过滤、表格导出与移动端布局', async ({page}) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/i/demo-main/statistics')
  await expect(page.getByRole('img', {name: '石油交互趋势图'})).toBeVisible()
  await page.getByLabel('图表类型').selectOption('candlestick')
  await page.getByLabel('采样粒度').selectOption('60')
  await page.screenshot({path: 'test-results/statistics-candlestick.png', fullPage: true})
  const download = page.waitForEvent('download')
  await page.getByRole('button', {name: '导出本类数据'}).click()
  expect((await download).suggestedFilename()).toMatch(/\.csv$/)
  for (const label of ['行动力与凭证', '大世界运行', '委托收益', '舰船经验', '短猫掉落']) {
    await page.getByRole('navigation', {name: '统计分类'}).getByRole('button', {name: label, exact: true}).click()
    await expect(page.getByText('前端模拟数据，仅用于交互验证。')).toBeVisible()
  }
  await page.getByRole('button', {name: '资源趋势', exact: true}).click()
  await page.getByLabel('图表起始时间').fill('2099-01-01T00:00')
  await expect(page.getByText('这段时间没有有效记录')).toBeVisible()
  await page.getByRole('button', {name: '全部时间', exact: true}).click()
  await page.getByLabel('图表类型').selectOption('area')
  await page.screenshot({path: 'test-results/statistics-resources-new.png', fullPage: true})
  await page.setViewportSize({width: 390, height: 844})
  await page.screenshot({path: 'test-results/statistics-mobile-new.png', fullPage: true})
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('下拉切换实例、创建入口与草稿隔离', async ({page}) => {
  await page.goto('/#/i/demo-main/task/Alas')
  const serial = page.locator('[id="Alas.Emulator.Serial"]')
  await expect(serial).toHaveValue('127.0.0.1:5555')
  await expect(page.locator('.rail')).toHaveCount(0)
  await expect(page.locator('.primary-nav').getByRole('link', {name: '系统设置'})).toBeVisible()
  await serial.fill('未保存的实例连接')
  await page.getByRole('button', {name: '切换实例'}).click()
  await page.getByRole('menuitemradio', {name: 'demo-alt', exact: true}).click()
  await page.getByRole('button', {name: '继续编辑'}).click()
  await expect(serial).toHaveValue('未保存的实例连接')
  await page.getByRole('button', {name: '切换实例'}).click()
  await page.getByRole('menuitemradio', {name: 'demo-alt', exact: true}).click()
  await page.getByRole('button', {name: '放弃修改并离开'}).click()
  await expect(page).toHaveURL(/demo-alt\/overview/)
  await page.getByRole('link', {name: '连接设置', exact: true}).click()
  await expect(serial).toHaveValue('127.0.0.1:5557')
  await page.getByRole('button', {name: '切换实例'}).click()
  await page.keyboard.press('End')
  await expect(page.getByRole('menuitem', {name: '创建实例'})).toBeFocused()
  await page.keyboard.press('Enter')
  const name = `mock_${Date.now()}`
  await page.getByRole('dialog').getByLabel('实例名称', {exact: true}).fill(name)
  await page.getByRole('dialog').getByRole('button', {name: '创建实例', exact: true}).click()
  await expect(page).toHaveURL(new RegExp(`${name}/task/Alas`))
  await expect(serial).toBeVisible()
})

test('配置字体、多行输入与 YAML 编辑保存、撤销及主题颜色', async ({page}) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/i/demo-main/task/Alas')
  const editor = page.locator('[id="Alas.Error.OnePushConfig"]')
  await expect(editor).toBeVisible()
  await expect(page.locator('.field-label small')).toHaveCount(0)
  expect(await page.locator('.field-label label').first().evaluate(node => parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(14)
  expect(await page.locator('html').evaluate(node => getComputedStyle(node).zoom)).toBe('1.25')
  const row = editor.locator('xpath=ancestor::div[contains(@class,"field-row")]')
  const label = await row.locator('.field-label').boundingBox()
  const input = await row.locator('.field-control').boundingBox()
  expect(input!.y).toBeGreaterThan(label!.y + label!.height)
  expect(input!.width).toBeGreaterThan(500)
  const yaml = '# 通知配置\nprovider: null\nretry: 3\nenabled: true\nmessage: "测试颜色"'
  await editor.fill(yaml)
  await page.getByRole('button', {name: '保存 1 项修改'}).click()
  await expect(page.getByRole('button', {name: '已保存', exact: true})).toBeVisible()
  await page.reload()
  await expect(editor).toHaveText(yaml.replaceAll('\n', ''))
  await editor.click()
  await page.keyboard.press('ControlOrMeta+End')
  await page.keyboard.type(' changed')
  await page.keyboard.press('ControlOrMeta+z')
  await expect(page.getByRole('button', {name: '已保存', exact: true})).toBeVisible()
  const token = editor.locator('span').filter({hasText: /^provider$/}).first()
  const lightColor = await token.evaluate(node => getComputedStyle(node).color)
  await row.scrollIntoViewIfNeeded()
  await page.screenshot({path: 'test-results/yaml-light.png'})
  await page.locator('.primary-nav').getByRole('link', {name: '系统设置'}).click()
  await page.getByLabel('界面主题').selectOption('dark')
  await page.goto('/#/i/demo-main/task/Alas')
  await expect(editor).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  expect(await token.evaluate(node => getComputedStyle(node).color)).not.toBe(lightColor)
  await row.scrollIntoViewIfNeeded()
  await page.screenshot({path: 'test-results/yaml-dark.png'})
  const textarea = page.locator('textarea').first()
  await expect(textarea).toBeVisible()
  expect((await textarea.boundingBox())!.height).toBeLessThan(80)
  expect(errors).toEqual([])
})

test('输入框随内容和宽度变化增高，删除后缩回单行', async ({page}) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/i/demo-alt/task/Alas')
  const input = page.locator('textarea').first()
  await expect(input).toBeVisible()
  await input.fill('单行')
  const single = (await input.boundingBox())!.height
  expect(single).toBeLessThan(80)
  await input.fill('第一行\n第二行\n第三行\n第四行')
  expect((await input.boundingBox())!.height).toBeGreaterThan(single + 70)
  await input.fill('单行')
  expect((await input.boundingBox())!.height).toBeCloseTo(single, 0)
  await input.fill('宽度变化会触发重新计算高度。'.repeat(25))
  const wide = (await input.boundingBox())!.height
  await page.setViewportSize({width: 390, height: 844})
  await expect.poll(async () => (await input.boundingBox())!.height).toBeGreaterThan(wide)
  await input.fill('')
  expect((await input.boundingBox())!.height).toBeCloseTo(single, 0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.setViewportSize({width: 1440, height: 1100})
  await page.getByRole('button', {name: '撤销修改', exact: true}).click()
  const yaml = page.locator('[id="Alas.Error.OnePushConfig"]')
  const scroller = yaml.locator('xpath=ancestor::div[contains(@class,"cm-scroller")]')
  const yamlSingle = (await scroller.boundingBox())!.height
  expect(yamlSingle).toBeLessThan(80)
  await yaml.fill('provider: null\nretry: 3\nenabled: true\nmessage: 测试')
  expect((await scroller.boundingBox())!.height).toBeGreaterThan(yamlSingle + 70)
  await yaml.fill('provider: null')
  expect((await scroller.boundingBox())!.height).toBeCloseTo(yamlSingle, 0)
  expect(errors).toEqual([])
})

test('存储空间为空时隐藏，有状态时显示完整 JSON 并可清除', async ({page}) => {
  await page.goto('/#/i/demo-alt/task/Alas')
  await expect(page.locator('textarea').first()).toBeVisible()
  await expect(page.locator('#group-Storage')).toHaveCount(0)
  await expect(page.locator('.group-nav').getByRole('link', {name: '任务状态'})).toHaveCount(0)
  await page.getByRole('textbox', {name: '搜索配置项', exact: true}).fill('Storage.Storage')
  await expect(page.getByText('没有找到配置项')).toBeVisible()
  await page.goto('/#/i/demo-error/task/Alas')
  await page.getByRole('textbox', {name: '搜索配置项', exact: true}).fill('')
  const storage = page.getByLabel('存储空间内容')
  await expect(storage).toBeVisible()
  expect(JSON.parse(await storage.innerText())).toEqual({failureCount: 3, lastError: '模拟器连接失败', retry: {enabled: false, remaining: 0}, tasks: ['Commission', 'Research']})
  await expect(storage).not.toContainText('[object Object]')
  const serial = page.locator('[id="Alas.Emulator.Serial"]')
  await serial.fill('保留其他字段的草稿')
  await page.locator('#group-Storage').scrollIntoViewIfNeeded()
  await page.screenshot({path: 'test-results/storage-state.png', animations: 'disabled'})
  await page.getByRole('button', {name: '清除存储空间'}).click()
  await expect(page.locator('#group-Storage')).toHaveCount(0)
  await expect(page.locator('.group-nav').getByRole('link', {name: '任务状态'})).toHaveCount(0)
  await expect(serial).toHaveValue('保留其他字段的草稿')
  await page.getByRole('button', {name: '撤销修改', exact: true}).click()
  await page.reload()
  await expect(page.locator('textarea').first()).toBeVisible()
  await expect(page.locator('#group-Storage')).toHaveCount(0)
})

test('语言偏好持久化，模拟启停、预览、统计和部署设置', async ({page}) => {
  await page.goto('/#/i/demo-main/settings')
  await page.getByLabel('界面语言').selectOption('en-US')
  await expect(page.locator('html')).toHaveAttribute('lang', 'en-US')
  await page.reload()
  await expect(page.getByLabel('界面语言')).toHaveValue('en-US')
  await page.goto('/#/i/demo-main/task/Alas')
  await expect(page.locator('label[for="Alas.Emulator.Serial"]')).toContainText('Serial')
  await page.locator('.primary-nav').getByRole('link', {name: '系统设置'}).click()
  await page.getByLabel('界面语言').selectOption('zh-CN')
  await page.getByLabel('监听端口').fill('23456')
  await page.getByRole('button', {name: '保存设置', exact: true}).click()
  await expect(page.getByRole('button', {name: '保存设置', exact: true})).toBeDisabled()
  await page.reload()
  await expect(page.getByLabel('监听端口')).toHaveValue('23456')
  await page.locator('.primary-nav').getByRole('link', {name: '运行总览'}).click()
  await page.getByRole('button', {name: '启动调度器'}).click()
  await expect(page.getByRole('button', {name: '停止运行'})).toBeVisible()
  await expect(page.getByLabel('运行日志内容')).toContainText('模拟调度器已启动')
  await page.getByRole('tab', {name: '截图', exact: true}).click()
  await expect(page.getByRole('img', {name: '任务最近一次截图'})).toBeVisible()
  await page.screenshot({path: 'test-results/mock-overview.png', fullPage: true})
  await page.getByRole('button', {name: '停止运行'}).click()
  await page.locator('.primary-nav').getByRole('link', {name: '资源统计'}).click()
  await expect(page.getByRole('img', {name: /交互趋势图/})).toBeVisible()
})

test('移动端放大布局无横向溢出，单栏导航可以收起', async ({page}) => {
  await page.setViewportSize({width: 390, height: 844})
  await page.goto('/#/i/demo-main/overview')
  await page.getByRole('button', {name: '打开导航'}).click()
  await page.getByRole('button', {name: '切换实例'}).click()
  await page.getByRole('menuitemradio', {name: 'demo-alt', exact: true}).click()
  await expect(page.locator('.app-shell')).not.toHaveClass(/mobile-open/)
  await page.getByRole('button', {name: '打开导航'}).click()
  await page.locator('.primary-nav').getByRole('link', {name: '系统设置'}).click()
  await expect(page.getByLabel('界面主题')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({path: 'test-results/mock-mobile.png', fullPage: true, animations: 'disabled'})
})
