import { expect, test } from '@playwright/test'

test('下拉切换实例、创建入口与草稿隔离', async ({page}) => {
  await page.goto('/#/i/demo-main/task/Alas')
  const serial = page.locator('[id="Alas.Emulator.Serial"]')
  await expect(serial).toHaveValue('127.0.0.1:5555')
  await expect(page.locator('.rail')).toHaveCount(0)
  await expect(page.locator('.primary-nav').getByRole('link', {name: '系统设置'})).toBeVisible()
  await serial.fill('未保存的实例连接')
  await page.getByRole('button', {name: '切换实例'}).click()
  await page.getByRole('menuitemradio', {name: 'demo-alt', exact: true}).click()
  await page.getByRole('button', {name: '继续编辑'}).click()
  await expect(serial).toHaveValue('未保存的实例连接')
  await page.getByRole('button', {name: '切换实例'}).click()
  await page.getByRole('menuitemradio', {name: 'demo-alt', exact: true}).click()
  await page.getByRole('button', {name: '放弃修改并离开'}).click()
  await expect(page).toHaveURL(/demo-alt\/overview/)
  await page.getByRole('link', {name: '连接设置', exact: true}).click()
  await expect(serial).toHaveValue('127.0.0.1:5557')
  await page.getByRole('button', {name: '切换实例'}).click()
  await page.keyboard.press('End')
  await expect(page.getByRole('menuitem', {name: '创建实例'})).toBeFocused()
  await page.keyboard.press('Enter')
  const name = `mock_${Date.now()}`
  await page.getByRole('dialog').getByLabel('实例名称', {exact: true}).fill(name)
  await page.getByRole('dialog').getByRole('button', {name: '创建实例', exact: true}).click()
  await expect(page).toHaveURL(new RegExp(`${name}/task/Alas`))
  await expect(serial).toBeVisible()
})

test('配置字体、多行输入与 YAML 编辑保存、撤销及主题颜色', async ({page}) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/i/demo-main/task/Alas')
  const editor = page.locator('[id="Alas.Error.OnePushConfig"]')
  await expect(editor).toBeVisible()
  await expect(page.locator('.field-label small')).toHaveCount(0)
  expect(await page.locator('.field-label label').first().evaluate(node => parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(14)
  expect(await page.locator('html').evaluate(node => getComputedStyle(node).zoom)).toBe('1.25')
  const row = editor.locator('xpath=ancestor::div[contains(@class,"field-row")]')
  const label = await row.locator('.field-label').boundingBox()
  const input = await row.locator('.field-control').boundingBox()
  expect(input!.y).toBeGreaterThan(label!.y + label!.height)
  expect(input!.width).toBeGreaterThan(500)
  const yaml = '# 通知配置\nprovider: null\nretry: 3\nenabled: true\nmessage: "测试颜色"'
  await editor.fill(yaml)
  await page.getByRole('button', {name: '保存 1 项修改'}).click()
  await expect(page.getByRole('button', {name: '已保存', exact: true})).toBeVisible()
  await page.reload()
  await expect(editor).toHaveText(yaml.replaceAll('\n', ''))
  await editor.click()
  await page.keyboard.press('ControlOrMeta+End')
  await page.keyboard.type(' changed')
  await page.keyboard.press('ControlOrMeta+z')
  await expect(page.getByRole('button', {name: '已保存', exact: true})).toBeVisible()
  const token = editor.locator('span').filter({hasText: /^provider$/}).first()
  const lightColor = await token.evaluate(node => getComputedStyle(node).color)
  await row.scrollIntoViewIfNeeded()
  await page.screenshot({path: 'test-results/yaml-light.png'})
  await page.locator('.primary-nav').getByRole('link', {name: '系统设置'}).click()
  await page.getByLabel('界面主题').selectOption('dark')
  await page.goto('/#/i/demo-main/task/Alas')
  await expect(editor).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  expect(await token.evaluate(node => getComputedStyle(node).color)).not.toBe(lightColor)
  await row.scrollIntoViewIfNeeded()
  await page.screenshot({path: 'test-results/yaml-dark.png'})
  const textarea = page.locator('textarea').first()
  await expect(textarea).toBeVisible()
  expect((await textarea.boundingBox())!.height).toBeLessThan(80)
  expect(errors).toEqual([])
})

test('输入框随内容和宽度变化增高，删除后缩回单行', async ({page}) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/i/demo-alt/task/Alas')
  const input = page.locator('textarea').first()
  await expect(input).toBeVisible()
  await input.fill('单行')
  const single = (await input.boundingBox())!.height
  expect(single).toBeLessThan(80)
  await input.fill('第一行\n第二行\n第三行\n第四行')
  expect((await input.boundingBox())!.height).toBeGreaterThan(single + 70)
  await input.fill('单行')
  expect((await input.boundingBox())!.height).toBeCloseTo(single, 0)
  await input.fill('宽度变化会触发重新计算高度。'.repeat(25))
  const wide = (await input.boundingBox())!.height
  await page.setViewportSize({width: 390, height: 844})
  await expect.poll(async () => (await input.boundingBox())!.height).toBeGreaterThan(wide)
  await input.fill('')
  expect((await input.boundingBox())!.height).toBeCloseTo(single, 0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.setViewportSize({width: 1440, height: 1100})
  await page.getByRole('button', {name: '撤销修改', exact: true}).click()
  const yaml = page.locator('[id="Alas.Error.OnePushConfig"]')
  const scroller = yaml.locator('xpath=ancestor::div[contains(@class,"cm-scroller")]')
  const yamlSingle = (await scroller.boundingBox())!.height
  expect(yamlSingle).toBeLessThan(80)
  await yaml.fill('provider: null\nretry: 3\nenabled: true\nmessage: 测试')
  expect((await scroller.boundingBox())!.height).toBeGreaterThan(yamlSingle + 70)
  await yaml.fill('provider: null')
  expect((await scroller.boundingBox())!.height).toBeCloseTo(yamlSingle, 0)
  expect(errors).toEqual([])
})

test('存储空间为空时隐藏，有状态时显示完整 JSON 并可清除', async ({page}) => {
  await page.goto('/#/i/demo-alt/task/Alas')
  await expect(page.locator('textarea').first()).toBeVisible()
  await expect(page.locator('#group-Storage')).toHaveCount(0)
  await expect(page.locator('.group-nav').getByRole('link', {name: '任务状态'})).toHaveCount(0)
  await page.getByRole('textbox', {name: '搜索配置项', exact: true}).fill('Storage.Storage')
  await expect(page.getByText('没有找到配置项')).toBeVisible()
  await page.goto('/#/i/demo-error/task/Alas')
  await page.getByRole('textbox', {name: '搜索配置项', exact: true}).fill('')
  const storage = page.getByLabel('存储空间内容')
  await expect(storage).toBeVisible()
  expect(JSON.parse(await storage.innerText())).toEqual({failureCount: 3, lastError: '模拟器连接失败', retry: {enabled: false, remaining: 0}, tasks: ['Commission', 'Research']})
  await expect(storage).not.toContainText('[object Object]')
  const serial = page.locator('[id="Alas.Emulator.Serial"]')
  await serial.fill('保留其他字段的草稿')
  await page.locator('#group-Storage').scrollIntoViewIfNeeded()
  await page.screenshot({path: 'test-results/storage-state.png', animations: 'disabled'})
  await page.getByRole('button', {name: '清除存储空间'}).click()
  await expect(page.locator('#group-Storage')).toHaveCount(0)
  await expect(page.locator('.group-nav').getByRole('link', {name: '任务状态'})).toHaveCount(0)
  await expect(serial).toHaveValue('保留其他字段的草稿')
  await page.getByRole('button', {name: '撤销修改', exact: true}).click()
  await page.reload()
  await expect(page.locator('textarea').first()).toBeVisible()
  await expect(page.locator('#group-Storage')).toHaveCount(0)
})

test('语言偏好持久化，模拟启停、预览、统计和部署设置', async ({page}) => {
  await page.goto('/#/i/demo-main/settings')
  await page.getByLabel('界面语言').selectOption('en-US')
  await expect(page.locator('html')).toHaveAttribute('lang', 'en-US')
  await page.reload()
  await expect(page.getByLabel('界面语言')).toHaveValue('en-US')
  await page.goto('/#/i/demo-main/task/Alas')
  await expect(page.locator('label[for="Alas.Emulator.Serial"]')).toContainText('Serial')
  await page.locator('.primary-nav').getByRole('link', {name: '系统设置'}).click()
  await page.getByLabel('界面语言').selectOption('zh-CN')
  await page.getByLabel('监听端口').fill('23456')
  await page.getByRole('button', {name: '保存设置', exact: true}).click()
  await expect(page.getByRole('button', {name: '保存设置', exact: true})).toBeDisabled()
  await page.reload()
  await expect(page.getByLabel('监听端口')).toHaveValue('23456')
  await page.locator('.primary-nav').getByRole('link', {name: '运行总览'}).click()
  await page.getByRole('button', {name: '启动调度器'}).click()
  await expect(page.getByRole('button', {name: '停止运行'})).toBeVisible()
  await expect(page.getByLabel('运行日志内容')).toContainText('模拟调度器已启动')
  await page.getByRole('button', {name: '获取截图'}).click()
  await expect(page.getByRole('img', {name: '模拟器当前画面'})).toBeVisible()
  await page.screenshot({path: 'test-results/mock-overview.png', fullPage: true})
  await page.getByRole('button', {name: '停止运行'}).click()
  await page.locator('.primary-nav').getByRole('link', {name: '资源统计'}).click()
  await expect(page.getByRole('img', {name: /资源变化图/})).toBeVisible()
})

test('移动端放大布局无横向溢出，单栏导航可以收起', async ({page}) => {
  await page.setViewportSize({width: 390, height: 844})
  await page.goto('/#/i/demo-main/overview')
  await page.getByRole('button', {name: '打开导航'}).click()
  await page.getByRole('button', {name: '切换实例'}).click()
  await page.getByRole('menuitemradio', {name: 'demo-alt', exact: true}).click()
  await expect(page.locator('.app-shell')).not.toHaveClass(/mobile-open/)
  await page.getByRole('button', {name: '打开导航'}).click()
  await page.locator('.primary-nav').getByRole('link', {name: '系统设置'}).click()
  await expect(page.getByLabel('界面主题')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({path: 'test-results/mock-mobile.png', fullPage: true, animations: 'disabled'})
})
